### ISSUE TITLE
Load Photomaker node gives error

### ISSUE THREAD

**Issue by MokkaBoss1** [shiimizu/ComfyUI-PhotoMaker#17]
since updated node today an errror is produced.

Error occurred when executing PhotoMakerLoader:

Error(s) in loading state_dict for PhotoMakerIDEncoder:
Missing key(s) in state_dict: "vision_model.embeddings.class_embedding", "vision_model.embeddings.patch_embedding.weight", "vision_model.embeddings.position_embedding.weight", "vision_model.pre_layrnorm.weight", "vision_model.pre_layrnorm.bias", "vision_model.encoder.layers.0.layer_norm1.weight", "vision_model.encoder.layers.0.layer_norm1.bias", "vision_model.encoder.layers.0.self_attn.q_proj.weight", "vision_model.encoder.layers.0.self_attn.q_proj.bias", "vision_model.encoder.layers.0.self_attn.k_proj.weight", "vision_model.encoder.layers.0.self_attn.k_proj.bias", "vision_model.encoder.layers.0.self_attn.v_proj.weight", "vision_model.encoder.layers.0.self_attn.v_proj.bias", "vision_model.encoder.layers.0.self_attn.out_proj.weight", "vision_model.encoder.layers.0.self_attn.out_proj.bias", "vision_model.encoder.layers.0.layer_norm2.weight", "vision_model.encoder.layers.0.layer_norm2.bias", "vision_model.encoder.layers.0.mlp.fc1.weight", "vision_model.encoder.layers.0.mlp.fc1.bias", "vision_model.encoder.layers.0.mlp.fc2.weight", "vision_model.encoder.layers.0.mlp.fc2.bias", "vision_model.encoder.layers.1.layer_norm1.weight", "vision_model.encoder.layers.1.layer_norm1.bias",

The node was working fine until I updated the node today.

**Comment by osxdoc** [comment]
Same here, since today comfyui update.

**Comment by Cgartvfx** [comment]
i also have it, how can i solve it?. Amazing Development Shiimizu, thank you for it!

**Comment by shiimizu** [comment]
> i also have it, how can i solve it?. Amazing Development Shiimizu, thank you for it!

1. Delete the `ConfyUI-PhotoMaker` or `ConfyUI-PhotoMaker-Plus` folder that’s in your `custom_nodes` folder.
2. Reinstall the node

**Comment by shiimizu** [comment]
1. Delete the `ConfyUI-PhotoMaker` or `ConfyUI-PhotoMaker-Plus` folder that’s in your `custom_nodes` folder.
2. Reinstall the node

**Comment by MokkaBoss1** [comment]
Thanks a million. Works fine now
